# Generated by Django 3.2.9 on 2021-12-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=500)),
                ('host', models.CharField(max_length=500)),
                ('your_post', models.CharField(max_length=500)),
                ('web_design', models.CharField(max_length=500)),
                ('work_field', models.CharField(max_length=500)),
                ('budget', models.CharField(max_length=500)),
                ('support', models.CharField(max_length=500)),
                ('cooperation', models.TextField()),
                ('details', models.TextField()),
                ('contacts', models.TextField()),
                ('site_system', models.CharField(default=1, max_length=200)),
                ('budget_amount', models.CharField(default=1, max_length=200)),
                ('who_support', models.CharField(default=1, max_length=200)),
                ('content_technical', models.CharField(default=1, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
