# Generated by Django 3.2.9 on 2021-12-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20211213_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='budget',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='comment',
            name='budget_amount',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='contacts',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_technical',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='cooperation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='host',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='comment',
            name='site_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='comment',
            name='site_system',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='support',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='comment',
            name='web_design',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='comment',
            name='who_support',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='work_field',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='comment',
            name='your_post',
            field=models.CharField(default='', max_length=500),
        ),
    ]
